
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testcase_llm_generator
    #url: jdbc:postgresql://localhost:5433/testcase_llm_generator
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: PatientHikariCP
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"

  jpa:
    hibernate:
      ddl-auto: update # Hibernate will auto-create/update tables for development
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
    show-sql: true
    open-in-view: false